security:
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: 'admin'
                        roles: 'ROLE_ADMIN'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            http_basic: ~
    access_control:
        - { path: ^/products/import, role: ROLE_ADMIN }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
